USE [BCMY_Stock];

CREATE TABLE TblExchangeRate(

	dateER DATE PRIMARY KEY NOT NULL,
	timeER TIME NOT NULL,
	usdValue DECIMAL(10,4) NOT NULL,
	euroValue DECIMAL(10,4) NOT NULL
);

SELECT * FROM TblExchangeRate;